<?php

require_once '../includes/session.php';
require_once '../includes/functions.php';
requireLogin('patient');



if (!isset($_GET['id']) || !is_numeric($_GET['id'])) {
    die("Invalid request");
}

$booking_id = $_GET['id'];
$patient_id = $_SESSION['user_id'];

$db = new Database();
$db->query("SELECT vb.*, h.hospital_name, h.address, h.phone, p.full_name 
            FROM vaccination_bookings vb
            JOIN hospitals h ON vb.hospital_id = h.id
            JOIN patients p ON vb.patient_id = p.id
            WHERE vb.id = :id AND vb.patient_id = :patient_id");
$db->bind(':id', $booking_id);
$db->bind(':patient_id', $patient_id);
$booking = $db->single();

if (!$booking || empty($booking['certificate_number'])) {
    die("Certificate not found or not issued yet.");
}

function formatDateTxt($date) {
    if (empty($date) || $date === '0000-00-00') return 'N/A';
    return date('F d, Y', strtotime($date));
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Vaccination Certificate</title>
    <style>
        body {
            background: #f0f0f0;
            font-family: 'Georgia', serif;
        }
        .certificate-box {
            background: white;
            padding: 50px;
            margin: 50px auto;
            width: 800px;
            border: 10px solid #0a5275;
            box-shadow: 0 0 10px rgba(0,0,0,0.3);
        }
        .certificate-header {
            text-align: center;
            border-bottom: 2px dashed #0a5275;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .certificate-header h1 {
            color: #0a5275;
            font-size: 32px;
            margin: 0;
            letter-spacing: 2px;
        }
        .certificate-body {
            font-size: 18px;
            color: #333;
            line-height: 1.8;
        }
        .field-label {
            font-weight: bold;
            color: #0a5275;
        }
        .certificate-footer {
            margin-top: 40px;
            text-align: center;
            border-top: 2px dashed #0a5275;
            padding-top: 20px;
        }
        .certificate-footer small {
            font-style: italic;
            color: #555;
        }
        @media print {
            body {
                background: none;
            }
            .certificate-box {
                box-shadow: none;
                border: 8px solid #0a5275;
            }
        }
    </style>
    <script>
        window.onload = function() {
            window.print();
        };
    </script>
</head>
<body>
    <div class="certificate-box">
        <div class="certificate-header">
            <h1>COVID-19 Vaccination Certificate</h1>
        </div>

        <div class="certificate-body">
            <p><span class="field-label">Patient Name:</span> <?= htmlspecialchars($booking['full_name']) ?></p>
            <p><span class="field-label">Hospital:</span> <?= htmlspecialchars($booking['hospital_name']) ?></p>
            <p><span class="field-label">Address:</span> <?= htmlspecialchars($booking['address']) ?></p>
            <p><span class="field-label">Phone:</span> <?= htmlspecialchars($booking['phone']) ?></p>
            <p><span class="field-label">Vaccine Name:</span> <?= htmlspecialchars($booking['vaccine_name']) ?></p>
            <p><span class="field-label">Dose Number:</span> <?= htmlspecialchars($booking['dose_number']) ?></p>
            <p><span class="field-label">Vaccination Date:</span> <?= formatDateTxt($booking['vaccination_date']) ?></p>
            <p><span class="field-label">Certificate Number:</span> <?= htmlspecialchars($booking['certificate_number']) ?></p>
            <p><span class="field-label">Status:</span> <?= htmlspecialchars($booking['status']) ?></p>
        </div>

        <div class="certificate-footer">
            <small>Generated by COVID Management System | <?= date("F d, Y") ?></small>
        </div>
    </div>
</body>
</html>
